### ISSUE TITLE
Datastore upload error

### ISSUE THREAD

**Issue by clairervh** [thenets/Easy-CKAN#15]
Hi Luiz,
I receive this error when I manually click to upload data to the datstore: "Error: Process completed but unable to post to result_url"

**Comment by thenets** [comment]
Hi, Claire.

I don't know why you receve this error. I create a fresh install on Ubuntu and everything work ok. I'll change some functions on Supervisor. Maybe this solve your problem.

I'll let you if I fix this problem.
