### ISSUE TITLE
How to install CKAN plugins from github?

### ISSUE THREAD

**Issue by vg-github** [thenets/Easy-CKAN#17]
I am trying to get a plugin installed via easyckan and it's not working, I get a one liner "File not found!".

Is it possible to add support in the future releases for plugins that outside the ckan's official list of plugins?

**Comment by thenets** [comment]
Hi, Vladimir.

By now, I'm supporting just the Harvest and DataStore/DataPusher. But a user creates installers for others plugins. You can check all available at:
https://github.com/thenets/Easy-CKAN/tree/master/installers/plugins

For example, if you want to install the "ckan_plugin_scheming.sh", you need to run: sudo easyckan plugin install scheming

Any other plugin, it's necessary to follow the instructions from http://extensions.ckan.org/

**Comment by vg-github** [comment]
Many thanks! I created pull request #18, this contains the installer for the s3filestore plugin.
