### ISSUE TITLE
No password entry for user 'ckan'

### ISSUE THREAD

**Issue by samisnunu** [thenets/Easy-CKAN#20]
Hi:
I just installed EasyCkan, to try it on (Ubuntu 14.4)
as per the instruction of installation I should then run the command:
`sudo easyckan server`
but I keep getting the message:
> No passwd entry for user 'ckan'

 even if I'm root

**Comment by samisnunu** [comment]
oops.. I missed the command:
`sudo` su -c "easyckan install"

**Comment by thenets** [comment]
If you have any problem, let me know ^^
