### ISSUE TITLE
Upgrading EasyCKAN to accommodate CKAN v2.6.1

### ISSUE THREAD

**Issue by samisnunu** [thenets/Easy-CKAN#21]
Hi Luiz,
Are you planning towards upgrading EasyCKAN's setup for CKAN v. 2.6.1 or awaiting v 2.7.1 to be released?

**Comment by thenets** [comment]
Do you need version 2.6.1? I already have a script for 2.6.1 version and I can launch it this week if you need.

**Comment by samisnunu** [comment]
Awesome, yes please,  I'm reading inside the installer file trying to see where to change the dependencies against version 2.6.1, 
Thanks for your response!

**Comment by thenets** [comment]
No problem.
I need to test a lot of things. In 4 or 5 days you will get the CKAN 2.6.1 or 2.6.2 version.
Any other question, talk with me at channel #easyckan at freenode.net .
Thanks.
