### ISSUE TITLE
Problemas relacionados aos scripts

### ISSUE THREAD

**Issue by leonardochacal** [thenets/Easy-CKAN#23]
Após o último comitt,ao tentar executar o /easy_ckan ,tem ocorrido o alerta que 👍:
/bin/bash^M: bad interpreter: No such file or directory
com a identificação de erros nas linhas do scrits que estão em branco.
Estou convertendo os scripts por meio do dos2unix.
Mais alguém tem tido esse problema?

**Comment by thenets** [comment]
Problema resolvido :)
O problema ocorreu quando eu editei a documentação do EasyCKAN no Windows.

Tudo corrigido no commit 328e532
