### ISSUE TITLE
/usr/lib/ckan folder not created

### ISSUE THREAD

**Issue by timgiles** [thenets/Easy-CKAN#8]
As above, I dont know why (have not investigated) but the /usr/lib/ckan folder is not being generated. Should be an easy fix.

**Comment by thenets** [comment]
Hi, Timgiles.

Have you ran all lines?
You need to install the "Easy CKAN" and after you need to install CKAN platform by running:

```
# easyckan install
```

What is your Ubuntu version?

**Comment by timgiles** [comment]
I ran using the instructions:

sudo su -c "apt-get update && apt-get upgrade -y"
sudo su -c "apt-get install git-core"
sudo su -c "cd /tmp && rm -rf ./Easy-CKAN && git clone https://github.com/thenets/Easy-CKAN.git && cd ./Easy-CKAN && ./easy_ckan.sh"
sudo su -c "easyckan install"

Ubuntu 14.04.05 Desktop ISO

Only other install before CKAN was openssh-server

**Comment by thenets** [comment]
Hi, Timgiles.

I'm running some tests and I don't why this doesn't work for you :/
Can you send me more information, such as a log data?

Thanks.

**Comment by timgiles** [comment]
Yes no problem. I will set up a VM this week coming. I was using Beta 0.2
and now 0.3. But I assume from your post that you have not changed
anything, so I will let you know how it functions. If it doesnt, expect
screen shots and the log.

Regards Timothy

**Comment by thenets** [comment]
The version 0.3 have improvements with plugins Harvest and DataPusher/DataStore.
Also has a lot of new functionality on EasyCKAN command line, like install plugins and interact with them.
And thanks :) if you send me screenshots, will help me a lot.

**Comment by timgiles** [comment]
OK, unfortunately it is hard to take a screenshot as it in the Stage 4 or 5. But, here is a subsequent error message (when it gets to step 7).

The message when it is trying to install is something like: Failed to create directory /usr/lib/ckan

If I : mkdir /usr/lib/ckan   and then rerun the install - everything is AOK

Regards Tim

![image](https://cloud.githubusercontent.com/assets/7511612/18310777/c37fb5b8-7500-11e6-91bd-5a3016d2e2c8.png)  
![capture](https://cloud.githubusercontent.com/assets/7511612/18310787/d493d5fa-7500-11e6-8fcc-14db199ca0d8.PNG)

**Comment by thenets** [comment]
Thanks a lot!
:D Fix added!
